# yaml-language-server: $schema=https://geoservices-int.camptocamp.com/github/schema.json

auto-review:
  conditions:
    - author: sbrunner
    - author: renovate[bot]

auto-merge:
  conditions:
    - author: sbrunner
