name: Continuous integration

on:
  pull_request:

permissions: {}

jobs:
  main:
    name: Continuous integration
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
      - name: GitHub event
        run: echo ${GITHUB_EVENT} | python3 -m json.tool
        env:
          GITHUB_EVENT: ${{ toJson(github) }}

      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
           path: ~/.cache/pre-commit
           key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
           restore-keys: "pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}\npre-commit-"
      - run: pip install pre-commit
      - run: pre-commit run --all-files
      - run: git diff --exit-code --patch > /tmp/pre-commit.patch || true
        if: failure()
      - uses: actions/upload-artifact@v4
        with:
          name: Apply pre-commit fix.patch
          path: /tmp/pre-commit.patch
          retention-days: 1
        if: failure()

      - run: echo "test" >> README.md
      - run: git diff --patch > patch.diff
      # Upload artifact
      - uses: actions/upload-artifact@v4
        with:
          name: do.diff
          path: patch.diff

      - run: git reset --hard HEAD^1 --
      - run: echo "test" > README.md
      - run: git add README.md
      - run: git config --global user.email "you@example.com"
      - run: git config --global user.name "Your Name"
      - run: git commit -m f
      - run: git log
      - run: git push
