name: Auto reviews, merge and close pull requests

on:
  pull_request:

permissions:
  pull-requests: write

jobs:
  auto-merge:
    name: Auto reviews, merge and close pull requests
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
      - name: Auto reviews Renovate updates
        uses: actions/github-script@v7
        with:
          script: |-
            github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE',
            })
