name: Print repository dispatch event

on:
  repository_dispatch:
    types:
      - published
    inputs:
      content:
        description: Published content
        required: true

jobs:
  print:
    runs-on: ubuntu-24.04
    name: Print repository dispatch event
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install 'c2cciutils<1.7'
      - run: c2cciutils-env
        env:
          GITHUB_EVENT: ${{ toJson(github) }}
      - name: Print the event
        run: |
          echo "Publish: ${{ toJson(github.event.client_payload.content) }}"
