name: Print repository dispatch event

on:
  repository_dispatch:
    types:
      - published
    inputs:
      content:
        description: Published content
        required: true

jobs:
  print:
    runs-on: ubuntu-24.04
    name: Print repository dispatch event
    timeout-minutes: 10

    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - run: pip install c2cciutils
      - run: c2cciutils-env
      - name: Print the event
        run: |
          echo "Publish: ${{ github.event.client_payload.publish }}"
